name: genzfit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Camera & ML
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.12.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  
  # 3D & AR
  model_viewer_plus: ^1.8.0
  
  # Notifications
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^18.0.1
  
  # UI/UX
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  photo_view: ^0.15.0
  
  # Chat
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  timeago: ^3.6.1
  file_picker: ^8.1.4
  open_filex: ^4.5.0
  
  # Utilities
  image_picker: ^1.0.4
  http: ^1.1.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  flutter_dotenv: ^5.1.0
  cloudinary_public: ^0.21.0
  firebase_storage: ^13.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - .env


  fonts:
     - family: Poppins
       fonts:
         - asset: assets/fonts/poppins/Poppins-Regular.ttf
         - asset: assets/fonts/poppins/Poppins-Bold.ttf
           weight: 700
         - asset: assets/fonts/poppins/Poppins-Medium.ttf
           weight: 500

     - family: Inter
       fonts:
         - asset: assets/fonts/inter/Inter-Regular.otf
         - asset: assets/fonts/inter/Inter-Bold.otf
           weight: 700
         - asset: assets/fonts/inter/Inter-Medium.otf
           weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
